### ISSUE TITLE
Article contents feature

### ISSUE THREAD

**Issue by wheat4714** [regek/facebook-marketplace-rss#1]
I've just installed this on my home server and connected to my local deals aggregator on Inoreader. I'm not using filters in the config file, as I already have all my filters managed centrally in Inoreader, and I can apply to Ebay/Gumtree/Shpock/FB-MP simultaneously and with regex.

These Facebook listing titles are too short and brief. It would be helpful if the RSS feed could include the listing descriptions as article contents.

**Comment by regek** [comment]
@wheat4714  I looked at adding the ad description, but it looks like there are no unique elements in the page except random `span class name`. Which is not a very reliable way to determine the correct section for description. If you have any suggestions, I'm open to it.
